node{

   def tomcatWeb = 'C:\\Users\\amal.chandra\\Downloads\\apache-tomcat-9.0.35\\webapps'
   def tomcatBin = 'C:\\Users\\amal.chandra\\Downloads\\apache-tomcat-9.0.35\\bin'
   def tomcatStatus = ''
   stage('SCM Checkout'){
     git 'https://github.com/Amal97/JenkinsWar.git'
   }
   stage('Compile-Package-create-war-file'){
      // Get maven home path
      def mvnHome =  tool name: 'Maven3.6.3', type: 'maven'   
      bat "C:\\Maven3.6.3\\bin\\mvn package"
   }
   
 stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
   
   stage('Deploy to Tomcat'){
     bat "copy target\\JenkinsWar.war \"${tomcatWeb}\\JenkinsWar.war\""
   }
      stage ('Start Tomcat Server') {
         sleep(time:5,unit:"SECONDS") 
         bat "${tomcatBin}\\startup.bat"
         sleep(time:100,unit:"SECONDS")
   }
}
